---
version: "3"
services:
  tor_proxy:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: armhf_alpine_tor_proxy
    container_name: torproxy
#    volumes:
#      - /etc/localtime:/etc/localtime
    ports:
      - 127.0.0.1:9050:9050
      - 127.0.0.1:9051:9051
    restart: unless-stopped

